<template>
  <div id="app">
    <Hero/>
    <!-- <FullPage/> -->
	
    <!-- <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>  -->
  </div>
</template>

<script>
import Hero from './components/Hero'
export default {
  name: 'App',
  components: {
  Hero, 
  },
 
}
</script>

<style>
html {
  /* scroll-behavior: smooth; */
}

body::-webkit-scrollbar {
  width: 1em;
  background: red;
  /* display: none; */
}
 
body::-webkit-scrollbar-track {
  box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
}
 
body::-webkit-scrollbar-thumb {
  background-color: darkgrey;
  outline: 1px solid slategrey;
}


@font-face {
	font-family: 'Conv_header_navbar';
	src: url('./font/header_navbar/fonts/header_navbar.eot');
	src: local('☺'), url('./font/header_navbar/fonts/header_navbar.woff') format('woff'), url('./font/header_navbar/fonts/header_navbar.ttf') format('truetype'), url('./font/header_navbar/fonts/header_navbar.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}



/** Generated by FG **/
@font-face {
	font-family: 'Conv_item';
	src: url('./font/item/fonts/item.eot');
	src: local('☺'), url('./font/item/fonts/item.woff') format('woff'), url('./font/item/fonts/item.ttf') format('truetype'), url('./font/item/fonts/item.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}






/** Generated by FG **/
@font-face {
	font-family: 'Conv_text';
	src: url('./font/text/fonts/text.eot');
	src: local('☺'), url('./font/text/fonts/text.woff') format('woff'), url('./font/text/fonts/text.ttf') format('truetype'), url('./font/text/fonts/text.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}




@font-face {
	font-family: 'Conv_link';
	src: url('./font/link/fonts/link.eot');
	src: local('☺'), url('./font/link/fonts/link.woff') format('woff'), url('./font/link/fonts/link.ttf') format('truetype'), url('./font/link/fonts/link.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}

@font-face {
	font-family: 'Conv_Header';
	src: url('./font/Header/fonts/Header.eot');
	src: local('☺'), url('./font/Header/fonts/Header.woff') format('woff'), url('./font/Header/fonts/Header.ttf') format('truetype'), url('./font/Header/fonts/Header.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}



@font-face {
	font-family: 'Cacefont';
  font-weight: 700;
  src: url('~@/font/Two/fonts/you2013.eot');
  src: url('./font/Two/fonts/you2013.eot') format('embedded-opentype'), /* IE < 9 */
  url('~@/font/Two/fonts/you2013.woff2') format('woff2'), /* Super Modern Browsers */
  url('~@/font/Two/fonts/you2013.woff') format('woff'); /* Firefox >= 3.6, any other modern browser */
		
}


@font-face {
	font-family: 'KalamRegular';
  font-weight: 900;
	src: url('~@/font/WTT/KalamRegular.eot');
	src: local('KalamRegular'), 
  url('~@/font/WTT/KalamRegular.woff') format('woff'),
  url('~@/font/WTT/KalamRegular.ttf') format('truetype');
}
.fontsforweb_fontid_80802 {
	font-family: 'KalamRegular' !important;
}






*{
  width: 100%;
  height: auto;
  overflow-x: hidden;
 box-sizing: border-box;
 padding: 0;
 margin: 0;
}
</style>